In [1]:
from cmath import nan

import numpy as np
import yfinance as yf
import pandas as pd
import datetime as dt

import hist_volatility
from riskfree_and_spot import *
from hist_volatility import *
from blackscholes import *
from binomial import *

In [2]:
option_style = "american" #european / american
valuation_date = "2026-08-04" #YYYY-MM-DD
ticker = "MSFT"
expiration = "2026-08-05"
strike = 487.5
option_type = "Call" # call / put
volatility_method = "historical" #historical / (implied /not yet implemented/)
hist_vol_lookback = 1 #in years

#BINOMIAL
n_for_binomial = 1500 #t0 + n steps

In [3]:
spot_price = get_spot_price_data(ticker=ticker, valuation_date=valuation_date)
t_t_m = option_tenor_calc(val_date=valuation_date, exp_date=expiration)
risk_free_rate = get_risk_free_rate(val_date=valuation_date, exp_date=expiration)
vol = get_volatility(ticker=ticker, val_date=valuation_date, lookback=hist_vol_lookback)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [4]:
#UPDATED_OPTION_CHAIN_QUARY

ticker_obj = yf.Ticker(ticker)
exps = ticker_obj.options
all_data = []

for date in exps:
    option_chain = ticker_obj.option_chain(date)
    if option_type.lower() =="call":
        type_chain = option_chain.calls
    elif option_type.lower() =="put":
        type_chain = option_chain.puts
    else:
        raise ValueError("option_style must be either 'call' or 'put'")
    type_chain["expiration"] = date

    all_data.append(type_chain)

all_data = pd.concat(all_data, ignore_index = True)
all_data

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,expiration
0,MSFT260810C00310000,2026-07-27 13:50:20+00:00,310.0,82.35,187.95,191.85,0.000000,0.000000,NaN,1,3.055666,True,REGULAR,USD,2026-08-10
1,MSFT260810C00320000,2026-08-07 19:53:53+00:00,320.0,180.93,178.25,181.90,48.729996,36.860813,146.0,1,1.859376,True,REGULAR,USD,2026-08-10
2,MSFT260810C00332500,2026-08-07 19:54:44+00:00,332.5,168.98,165.95,169.35,50.629997,42.779890,66.0,2,1.839845,True,REGULAR,USD,2026-08-10
3,MSFT260810C00335000,2026-07-30 13:48:30+00:00,335.0,115.88,163.25,166.85,0.000000,0.000000,NaN,2,1.625002,True,REGULAR,USD,2026-08-10
4,MSFT260810C00340000,2026-08-07 19:51:30+00:00,340.0,160.72,158.25,161.85,64.650000,67.294680,8.0,1,1.570315,True,REGULAR,USD,2026-08-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1537,MSFT281215C00710000,2026-08-07 13:39:24+00:00,710.0,59.06,55.95,59.00,3.310001,5.937222,1.0,316,0.385878,False,REGULAR,USD,2028-12-15
1538,MSFT281215C00715000,2026-08-05 18:54:20+00:00,715.0,52.00,55.00,58.50,0.000000,0.000000,19.0,868,0.387350,False,REGULAR,USD,2028-12-15
1539,MSFT281215C00720000,2026-08-07 17:58:51+00:00,720.0,55.37,53.90,57.50,-0.080002,-0.144277,1.0,895,0.387053,False,REGULAR,USD,2028-12-15
1540,MSFT281215C00725000,2026-08-07 19:53:58+00:00,725.0,54.75,53.20,55.30,0.349998,0.643379,700.0,1885,0.382567,False,REGULAR,USD,2028-12-15
1541,MSFT281215C00730000,2026-08-07 19:25:06+00:00,730.0,53.89,52.25,54.30,-0.389999,-0.718496,32.0,7907,0.382143,False,REGULAR,USD,2028-12-15

In [5]:
raw_data = all_data

In [6]:
# raw_data = pd.read_csv("../data/option_data.csv")

In [7]:
#TENOR_CALC

tenor_list = []

for i, row in raw_data.iterrows():
    exp_date = row["expiration"]
    tenor = option_tenor_calc(val_date=valuation_date, exp_date=exp_date)
    tenor_list.append(tenor)

raw_data["tenor"] = tenor_list

In [8]:
#RF_RATE_CALC

exp_list = raw_data["expiration"].unique()

rf_for_exp_dict = {
    exp: get_risk_free_rate(val_date=valuation_date, exp_date=exp)
    for exp in exp_list
}

raw_data["rf_rate"] = raw_data["expiration"].map(rf_for_exp_dict)

In [9]:
#MID_PRICE_CALC

mid_price_list = []

for i, row in raw_data.iterrows():
    mid = (row["bid"] + row["ask"]) / 2
    mid_price_list.append(mid)

raw_data["mid_price"] = mid_price_list

In [10]:
#SPREAD_CALC

spread_list = []
for i, row in raw_data.iterrows():
    spread = row["ask"] - row["bid"]
    spread_list.append(spread)

raw_data["spread"] = spread_list

In [11]:
#LIQUIDITY_CUT
raw_data_lq_filter = raw_data[
    (raw_data["bid"] > 0) &
    (raw_data["ask"] > 0) &
    (raw_data["volume"] > 3) &
    (raw_data["openInterest"] > 0) &
    (raw_data["strike"] > 0.7 * spot_price) &
    (raw_data["strike"] < 1.3 * spot_price) &
    ((raw_data["spread"] < (0.3 * raw_data["mid_price"])) |
    (raw_data["spread"] <= 0.05))
]

raw_data_lq_filter

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,expiration,tenor,rf_rate,mid_price,spread
7,MSFT260810C00357500,2026-08-03 19:42:33+00:00,357.5,133.21,140.95,144.35,0.000000,0.000000,10.0,11,1.541018,True,REGULAR,USD,2026-08-10,0.016438,0.037800,142.650,3.40
8,MSFT260810C00360000,2026-08-05 19:35:57+00:00,360.0,130.55,138.15,141.85,0.000000,0.000000,20.0,24,1.156254,True,REGULAR,USD,2026-08-10,0.016438,0.037800,140.000,3.70
11,MSFT260810C00370000,2026-08-07 19:52:50+00:00,370.0,130.63,128.35,131.85,48.130005,58.339397,16.0,21,1.335941,True,REGULAR,USD,2026-08-10,0.016438,0.037800,130.100,3.50
12,MSFT260810C00372500,2026-08-07 19:52:50+00:00,372.5,128.15,125.95,129.40,50.459990,64.950430,10.0,1,1.396487,True,REGULAR,USD,2026-08-10,0.016438,0.037800,127.675,3.45
17,MSFT260810C00387500,2026-08-07 19:53:36+00:00,387.5,113.95,110.70,114.35,3.839996,3.487418,8.0,11,1.015630,True,REGULAR,USD,2026-08-10,0.016438,0.037800,112.525,3.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,MSFT281215C00600000,2026-08-07 19:54:26+00:00,600.0,85.53,84.60,87.30,-0.470001,-0.546513,42.0,6395,0.396590,False,REGULAR,USD,2028-12-15,2.367123,0.042159,85.950,2.70
1518,MSFT281215C00615000,2026-08-05 13:39:08+00:00,615.0,75.65,79.00,82.25,0.000000,0.000000,10.0,94,0.393141,False,REGULAR,USD,2028-12-15,2.367123,0.042159,80.625,3.25
1520,MSFT281215C00625000,2026-08-05 16:41:48+00:00,625.0,73.25,76.70,79.35,0.000000,0.000000,37.0,975,0.392004,False,REGULAR,USD,2028-12-15,2.367123,0.042159,78.025,2.65
1522,MSFT281215C00635000,2026-08-07 19:53:58+00:00,635.0,75.22,73.35,77.25,21.110000,39.013123,700.0,69,0.393210,False,REGULAR,USD,2028-12-15,2.367123,0.042159,75.300,3.90
1523,MSFT281215C00640000,2026-08-07 16:14:42+00:00,640.0,75.10,72.25,75.30,5.049995,7.209130,7.0,112,0.390761,False,REGULAR,USD,2028-12-15,2.367123,0.042159,73.775,3.05

In [12]:
#NO_ARGBITRAGE_CHECK (rewrite as violation for consistency)

no_arbitrage_flag_list = []

for i, row in raw_data_lq_filter.iterrows():
    k = row["strike"]
    rf = row["rf_rate"]
    t = row["tenor"]
    mid = row["mid_price"]
    q = 0.0
    lower_bound = max(0, spot_price * np.exp(-q * t) - (k * np.exp(-rf * t)))
    upper_bound = spot_price
    if mid > lower_bound and mid < upper_bound:
        arbitrage_viol_flag = False
    else:
        arbitrage_viol_flag = True
    no_arbitrage_flag_list.append(arbitrage_viol_flag)

raw_data_lq_filter["arbitrage_viol"] = no_arbitrage_flag_list

raw_data_lq_filter

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,expiration,tenor,rf_rate,mid_price,spread,arbitrage_viol
7,MSFT260810C00357500,2026-08-03 19:42:33+00:00,357.5,133.21,140.95,144.35,0.000000,0.000000,10.0,11,1.541018,True,REGULAR,USD,2026-08-10,0.016438,0.037800,142.650,3.40,False
8,MSFT260810C00360000,2026-08-05 19:35:57+00:00,360.0,130.55,138.15,141.85,0.000000,0.000000,20.0,24,1.156254,True,REGULAR,USD,2026-08-10,0.016438,0.037800,140.000,3.70,False
11,MSFT260810C00370000,2026-08-07 19:52:50+00:00,370.0,130.63,128.35,131.85,48.130005,58.339397,16.0,21,1.335941,True,REGULAR,USD,2026-08-10,0.016438,0.037800,130.100,3.50,False
12,MSFT260810C00372500,2026-08-07 19:52:50+00:00,372.5,128.15,125.95,129.40,50.459990,64.950430,10.0,1,1.396487,True,REGULAR,USD,2026-08-10,0.016438,0.037800,127.675,3.45,False
17,MSFT260810C00387500,2026-08-07 19:53:36+00:00,387.5,113.95,110.70,114.35,3.839996,3.487418,8.0,11,1.015630,True,REGULAR,USD,2026-08-10,0.016438,0.037800,112.525,3.65,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,MSFT281215C00600000,2026-08-07 19:54:26+00:00,600.0,85.53,84.60,87.30,-0.470001,-0.546513,42.0,6395,0.396590,False,REGULAR,USD,2028-12-15,2.367123,0.042159,85.950,2.70,False
1518,MSFT281215C00615000,2026-08-05 13:39:08+00:00,615.0,75.65,79.00,82.25,0.000000,0.000000,10.0,94,0.393141,False,REGULAR,USD,2028-12-15,2.367123,0.042159,80.625,3.25,False
1520,MSFT281215C00625000,2026-08-05 16:41:48+00:00,625.0,73.25,76.70,79.35,0.000000,0.000000,37.0,975,0.392004,False,REGULAR,USD,2028-12-15,2.367123,0.042159,78.025,2.65,False
1522,MSFT281215C00635000,2026-08-07 19:53:58+00:00,635.0,75.22,73.35,77.25,21.110000,39.013123,700.0,69,0.393210,False,REGULAR,USD,2028-12-15,2.367123,0.042159,75.300,3.90,False
1523,MSFT281215C00640000,2026-08-07 16:14:42+00:00,640.0,75.10,72.25,75.30,5.049995,7.209130,7.0,112,0.390761,False,REGULAR,USD,2028-12-15,2.367123,0.042159,73.775,3.05,False

In [13]:
#MONOTONICITY_CHECK

price_col = "mid_price"
strike_col = "strike"
expiry_col = "expiration"

monot_check = raw_data_lq_filter.sort_values([expiry_col, strike_col]).copy()
monot_check["monotonicity_viol"] = False

for exp, group in monot_check.groupby(expiry_col):
    idx = group.index
    prices = group[price_col].values

    diffs = np.diff(prices)
    flags = np.where(diffs > 0)[0]

    for i in flags:
        monot_check.loc[idx[i + 1], "monotonicity_viol"] = True

monot_check

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,...,inTheMoney,contractSize,currency,expiration,tenor,rf_rate,mid_price,spread,arbitrage_viol,monotonicity_viol
7,MSFT260810C00357500,2026-08-03 19:42:33+00:00,357.5,133.21,140.95,144.35,0.000000,0.000000,10.0,11,...,True,REGULAR,USD,2026-08-10,0.016438,0.037800,142.650,3.40,False,False
8,MSFT260810C00360000,2026-08-05 19:35:57+00:00,360.0,130.55,138.15,141.85,0.000000,0.000000,20.0,24,...,True,REGULAR,USD,2026-08-10,0.016438,0.037800,140.000,3.70,False,False
11,MSFT260810C00370000,2026-08-07 19:52:50+00:00,370.0,130.63,128.35,131.85,48.130005,58.339397,16.0,21,...,True,REGULAR,USD,2026-08-10,0.016438,0.037800,130.100,3.50,False,False
12,MSFT260810C00372500,2026-08-07 19:52:50+00:00,372.5,128.15,125.95,129.40,50.459990,64.950430,10.0,1,...,True,REGULAR,USD,2026-08-10,0.016438,0.037800,127.675,3.45,False,False
17,MSFT260810C00387500,2026-08-07 19:53:36+00:00,387.5,113.95,110.70,114.35,3.839996,3.487418,8.0,11,...,True,REGULAR,USD,2026-08-10,0.016438,0.037800,112.525,3.65,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,MSFT281215C00600000,2026-08-07 19:54:26+00:00,600.0,85.53,84.60,87.30,-0.470001,-0.546513,42.0,6395,...,False,REGULAR,USD,2028-12-15,2.367123,0.042159,85.950,2.70,False,False
1518,MSFT281215C00615000,2026-08-05 13:39:08+00:00,615.0,75.65,79.00,82.25,0.000000,0.000000,10.0,94,...,False,REGULAR,USD,2028-12-15,2.367123,0.042159,80.625,3.25,False,False
1520,MSFT281215C00625000,2026-08-05 16:41:48+00:00,625.0,73.25,76.70,79.35,0.000000,0.000000,37.0,975,...,False,REGULAR,USD,2028-12-15,2.367123,0.042159,78.025,2.65,False,False
1522,MSFT281215C00635000,2026-08-07 19:53:58+00:00,635.0,75.22,73.35,77.25,21.110000,39.013123,700.0,69,...,False,REGULAR,USD,2028-12-15,2.367123,0.042159,75.300,3.90,False,False
1523,MSFT281215C00640000,2026-08-07 16:14:42+00:00,640.0,75.10,72.25,75.30,5.049995,7.209130,7.0,112,...,False,REGULAR,USD,2028-12-15,2.367123,0.042159,73.775,3.05,False,False

In [14]:
#CONVEXITY_CHECK
price_col = "mid_price"
strike_col = "strike"
expiry_col = "expiration"

convex_check = monot_check.sort_values([expiry_col, strike_col]).copy()
convex_check["convexity_viol"] = False

for exp, group in convex_check.groupby(expiry_col):
    idx = group.index.values
    K = group[strike_col].values
    C = group[price_col].values

    for i in range(1, len(K)-1):
        K1, K2, K3 = K[i - 1], K[i], K[i + 1]
        C1, C2, C3 = C[i - 1], C[i], C[i + 1]

        weight = (K3 - K2) / (K3 - K1)
        limit = weight * C1 + (1 - weight) * C2

        if C2 > limit + 1e-8:
            convex_check.loc[idx[i],"convexity_viol"] = True

convex_check

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,...,contractSize,currency,expiration,tenor,rf_rate,mid_price,spread,arbitrage_viol,monotonicity_viol,convexity_viol
7,MSFT260810C00357500,2026-08-03 19:42:33+00:00,357.5,133.21,140.95,144.35,0.000000,0.000000,10.0,11,...,REGULAR,USD,2026-08-10,0.016438,0.037800,142.650,3.40,False,False,False
8,MSFT260810C00360000,2026-08-05 19:35:57+00:00,360.0,130.55,138.15,141.85,0.000000,0.000000,20.0,24,...,REGULAR,USD,2026-08-10,0.016438,0.037800,140.000,3.70,False,False,False
11,MSFT260810C00370000,2026-08-07 19:52:50+00:00,370.0,130.63,128.35,131.85,48.130005,58.339397,16.0,21,...,REGULAR,USD,2026-08-10,0.016438,0.037800,130.100,3.50,False,False,False
12,MSFT260810C00372500,2026-08-07 19:52:50+00:00,372.5,128.15,125.95,129.40,50.459990,64.950430,10.0,1,...,REGULAR,USD,2026-08-10,0.016438,0.037800,127.675,3.45,False,False,False
17,MSFT260810C00387500,2026-08-07 19:53:36+00:00,387.5,113.95,110.70,114.35,3.839996,3.487418,8.0,11,...,REGULAR,USD,2026-08-10,0.016438,0.037800,112.525,3.65,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,MSFT281215C00600000,2026-08-07 19:54:26+00:00,600.0,85.53,84.60,87.30,-0.470001,-0.546513,42.0,6395,...,REGULAR,USD,2028-12-15,2.367123,0.042159,85.950,2.70,False,False,False
1518,MSFT281215C00615000,2026-08-05 13:39:08+00:00,615.0,75.65,79.00,82.25,0.000000,0.000000,10.0,94,...,REGULAR,USD,2028-12-15,2.367123,0.042159,80.625,3.25,False,False,False
1520,MSFT281215C00625000,2026-08-05 16:41:48+00:00,625.0,73.25,76.70,79.35,0.000000,0.000000,37.0,975,...,REGULAR,USD,2028-12-15,2.367123,0.042159,78.025,2.65,False,False,False
1522,MSFT281215C00635000,2026-08-07 19:53:58+00:00,635.0,75.22,73.35,77.25,21.110000,39.013123,700.0,69,...,REGULAR,USD,2028-12-15,2.367123,0.042159,75.300,3.90,False,False,False
1523,MSFT281215C00640000,2026-08-07 16:14:42+00:00,640.0,75.10,72.25,75.30,5.049995,7.209130,7.0,112,...,REGULAR,USD,2028-12-15,2.367123,0.042159,73.775,3.05,False,False,False

In [15]:
#BISECTIONAL_IV_SEARCH

def bisection_iv(opt_type, target, s, k, t, r, q, sigma_lo=1e-4, sigma_hi=5, tol=1e-6, iter=100):

    if opt_type.lower() == "call":
        f_lo = bs_call(S=s, K=k, T=t, r=r, vol=sigma_lo, q=q) - target
        f_hi = bs_call(S=s, K=k, T=t, r=r, vol=sigma_hi, q=q) - target
    elif opt_type.lower() == "put":
        f_lo = bs_put(S=s, K=k, T=t, r=r, vol=sigma_lo) - target
        f_hi = bs_put(S=s, K=k, T=t, r=r, vol=sigma_hi) - target
    else:
        raise ValueError ("option_type must be either 'call' or 'put'")

    if f_lo * f_hi > 0:
        return None

    for _ in range(iter):
        sigma_mid = (sigma_lo + sigma_hi) / 2
        if opt_type.lower() == "call":
            f_mid = bs_call(S=s, K=k, T=t, r=r, vol=sigma_mid, q=q) - target
        elif opt_type.lower() == "put":
            f_mid = bs_put(S=s, K=k, T=t, r=r, vol=sigma_mid, q=q) - target

        if abs(f_mid) < tol or (sigma_hi - sigma_lo) < tol:
            return sigma_mid

        if f_lo * f_mid < 0:
            sigma_hi = sigma_mid
        else:
            sigma_lo = sigma_mid
            f_lo = f_mid

    return (sigma_lo + sigma_hi) / 2

In [16]:
#BISECTIONAL_IV_SEARCH
iv_calc = convex_check

iv_list = []

for i, row in iv_calc.iterrows():
    iv= bisection_iv(
        opt_type=option_type,
        q=0.0,
        target=row["mid_price"],
        s=spot_price,
        k=row["strike"],
        t=row["tenor"],
        r=row["rf_rate"],
        sigma_lo=1e-4,
        sigma_hi=5,
        tol=1e-6,
        iter=100
    )
    iv_list.append(iv)

iv_calc["iv_bisec"]=iv_list

iv_calc

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,...,currency,expiration,tenor,rf_rate,mid_price,spread,arbitrage_viol,monotonicity_viol,convexity_viol,iv_bisec
7,MSFT260810C00357500,2026-08-03 19:42:33+00:00,357.5,133.21,140.95,144.35,0.000000,0.000000,10.0,11,...,USD,2026-08-10,0.016438,0.037800,142.650,3.40,False,False,False,2.170022
8,MSFT260810C00360000,2026-08-05 19:35:57+00:00,360.0,130.55,138.15,141.85,0.000000,0.000000,20.0,24,...,USD,2026-08-10,0.016438,0.037800,140.000,3.70,False,False,False,2.120847
11,MSFT260810C00370000,2026-08-07 19:52:50+00:00,370.0,130.63,128.35,131.85,48.130005,58.339397,16.0,21,...,USD,2026-08-10,0.016438,0.037800,130.100,3.50,False,False,False,1.989830
12,MSFT260810C00372500,2026-08-07 19:52:50+00:00,372.5,128.15,125.95,129.40,50.459990,64.950430,10.0,1,...,USD,2026-08-10,0.016438,0.037800,127.675,3.45,False,False,False,1.961625
17,MSFT260810C00387500,2026-08-07 19:53:36+00:00,387.5,113.95,110.70,114.35,3.839996,3.487418,8.0,11,...,USD,2026-08-10,0.016438,0.037800,112.525,3.65,False,False,False,1.744177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,MSFT281215C00600000,2026-08-07 19:54:26+00:00,600.0,85.53,84.60,87.30,-0.470001,-0.546513,42.0,6395,...,USD,2028-12-15,2.367123,0.042159,85.950,2.70,False,False,False,0.347960
1518,MSFT281215C00615000,2026-08-05 13:39:08+00:00,615.0,75.65,79.00,82.25,0.000000,0.000000,10.0,94,...,USD,2028-12-15,2.367123,0.042159,80.625,3.25,False,False,False,0.344646
1520,MSFT281215C00625000,2026-08-05 16:41:48+00:00,625.0,73.25,76.70,79.35,0.000000,0.000000,37.0,975,...,USD,2028-12-15,2.367123,0.042159,78.025,2.65,False,False,False,0.345178
1522,MSFT281215C00635000,2026-08-07 19:53:58+00:00,635.0,75.22,73.35,77.25,21.110000,39.013123,700.0,69,...,USD,2028-12-15,2.367123,0.042159,75.300,3.90,False,False,False,0.344983
1523,MSFT281215C00640000,2026-08-07 16:14:42+00:00,640.0,75.10,72.25,75.30,5.049995,7.209130,7.0,112,...,USD,2028-12-15,2.367123,0.042159,73.775,3.05,False,False,False,0.344233

In [17]:
iv_filter = iv_calc[
    (iv_calc["arbitrage_viol"] == False) &
    (iv_calc["monotonicity_viol"] == False) &
    (iv_calc["convexity_viol"] == False)
]
iv_filter

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,...,currency,expiration,tenor,rf_rate,mid_price,spread,arbitrage_viol,monotonicity_viol,convexity_viol,iv_bisec
7,MSFT260810C00357500,2026-08-03 19:42:33+00:00,357.5,133.21,140.95,144.35,0.000000,0.000000,10.0,11,...,USD,2026-08-10,0.016438,0.037800,142.650,3.40,False,False,False,2.170022
8,MSFT260810C00360000,2026-08-05 19:35:57+00:00,360.0,130.55,138.15,141.85,0.000000,0.000000,20.0,24,...,USD,2026-08-10,0.016438,0.037800,140.000,3.70,False,False,False,2.120847
11,MSFT260810C00370000,2026-08-07 19:52:50+00:00,370.0,130.63,128.35,131.85,48.130005,58.339397,16.0,21,...,USD,2026-08-10,0.016438,0.037800,130.100,3.50,False,False,False,1.989830
12,MSFT260810C00372500,2026-08-07 19:52:50+00:00,372.5,128.15,125.95,129.40,50.459990,64.950430,10.0,1,...,USD,2026-08-10,0.016438,0.037800,127.675,3.45,False,False,False,1.961625
17,MSFT260810C00387500,2026-08-07 19:53:36+00:00,387.5,113.95,110.70,114.35,3.839996,3.487418,8.0,11,...,USD,2026-08-10,0.016438,0.037800,112.525,3.65,False,False,False,1.744177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,MSFT281215C00600000,2026-08-07 19:54:26+00:00,600.0,85.53,84.60,87.30,-0.470001,-0.546513,42.0,6395,...,USD,2028-12-15,2.367123,0.042159,85.950,2.70,False,False,False,0.347960
1518,MSFT281215C00615000,2026-08-05 13:39:08+00:00,615.0,75.65,79.00,82.25,0.000000,0.000000,10.0,94,...,USD,2028-12-15,2.367123,0.042159,80.625,3.25,False,False,False,0.344646
1520,MSFT281215C00625000,2026-08-05 16:41:48+00:00,625.0,73.25,76.70,79.35,0.000000,0.000000,37.0,975,...,USD,2028-12-15,2.367123,0.042159,78.025,2.65,False,False,False,0.345178
1522,MSFT281215C00635000,2026-08-07 19:53:58+00:00,635.0,75.22,73.35,77.25,21.110000,39.013123,700.0,69,...,USD,2028-12-15,2.367123,0.042159,75.300,3.90,False,False,False,0.344983
1523,MSFT281215C00640000,2026-08-07 16:14:42+00:00,640.0,75.10,72.25,75.30,5.049995,7.209130,7.0,112,...,USD,2028-12-15,2.367123,0.042159,73.775,3.05,False,False,False,0.344233

In [19]:
#FORWARD + MONEYNESS (DIVYIELDEDIT)

forward_list = []

q = 0.0

for i, row in iv_filter.iterrows():
    forward = spot_price * np.exp((row["rf_rate"] - q) * row["tenor"])
    forward_list.append(forward)

iv_filter["forward"] = forward_list

moneyness_list = []

for i, row in iv_filter.iterrows():
    moneyness = np.log(row["strike"] / row["forward"])
    moneyness_list.append(moneyness)

iv_filter["log_moneyness"] = moneyness_list
iv_filter

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,...,tenor,rf_rate,mid_price,spread,arbitrage_viol,monotonicity_viol,convexity_viol,iv_bisec,forward,log_moneyness
7,MSFT260810C00357500,2026-08-03 19:42:33+00:00,357.5,133.21,140.95,144.35,0.000000,0.000000,10.0,11,...,0.016438,0.037800,142.650,3.40,False,False,False,2.170022,493.11631,-0.321610
8,MSFT260810C00360000,2026-08-05 19:35:57+00:00,360.0,130.55,138.15,141.85,0.000000,0.000000,20.0,24,...,0.016438,0.037800,140.000,3.70,False,False,False,2.120847,493.11631,-0.314641
11,MSFT260810C00370000,2026-08-07 19:52:50+00:00,370.0,130.63,128.35,131.85,48.130005,58.339397,16.0,21,...,0.016438,0.037800,130.100,3.50,False,False,False,1.989830,493.11631,-0.287242
12,MSFT260810C00372500,2026-08-07 19:52:50+00:00,372.5,128.15,125.95,129.40,50.459990,64.950430,10.0,1,...,0.016438,0.037800,127.675,3.45,False,False,False,1.961625,493.11631,-0.280508
17,MSFT260810C00387500,2026-08-07 19:53:36+00:00,387.5,113.95,110.70,114.35,3.839996,3.487418,8.0,11,...,0.016438,0.037800,112.525,3.65,False,False,False,1.744177,493.11631,-0.241029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,MSFT281215C00600000,2026-08-07 19:54:26+00:00,600.0,85.53,84.60,87.30,-0.470001,-0.546513,42.0,6395,...,2.367123,0.042159,85.950,2.70,False,False,False,0.347960,544.52805,0.097010
1518,MSFT281215C00615000,2026-08-05 13:39:08+00:00,615.0,75.65,79.00,82.25,0.000000,0.000000,10.0,94,...,2.367123,0.042159,80.625,3.25,False,False,False,0.344646,544.52805,0.121703
1520,MSFT281215C00625000,2026-08-05 16:41:48+00:00,625.0,73.25,76.70,79.35,0.000000,0.000000,37.0,975,...,2.367123,0.042159,78.025,2.65,False,False,False,0.345178,544.52805,0.137832
1522,MSFT281215C00635000,2026-08-07 19:53:58+00:00,635.0,75.22,73.35,77.25,21.110000,39.013123,700.0,69,...,2.367123,0.042159,75.300,3.90,False,False,False,0.344983,544.52805,0.153706
1523,MSFT281215C00640000,2026-08-07 16:14:42+00:00,640.0,75.10,72.25,75.30,5.049995,7.209130,7.0,112,...,2.367123,0.042159,73.775,3.05,False,False,False,0.344233,544.52805,0.161549